#!/bin/bash

VERSION=v0.8.500
GLAM=GlamorousToolkitLinux64-$VERSION

if [[ ! -d $GLAM ]]
then
    echo
    echo installing $GLAM ...
    wget -q https://dl.feenk.com/gt/GlamorousToolkitLinux64-$VERSION.zip
    unzip -q Glamorous*.zip
    rm Glamorous*.zip
fi

pushd $GLAM >& /dev/null

    MISSING=$(ldd libSkia.so | grep "not found")
    if [[ "$MISSING" != "" ]]
    then
        echo must replace package libstdcc++6 with a newer one from 20.04
            exit 1
    fi

    echo
    echo starting $GLAM
    ./glamoroustoolkit GlamorousToolkit.image st ../load.st --no-quit --interactive

popd >& /dev/null

git status
