#!/bin/bash

VERSION=v0.8.493
GLAM=GlamorousToolkitLinux64-$VERSION

if [[ ! -d $GLAM ]]
then
    echo
    echo installing $GLAM ...
    wget -q https://dl.feenk.com/gt/GlamorousToolkitLinux64-$VERSION.zip
    unzip -q Glamorous*.zip
    rm Glamorous*.zip
fi

pushd $GLAM >& /dev/null

    MISSING=$(ldd libSkia.so | grep "not found")
    if [[ "$MISSING" != "" ]]
    then
        LIB=libstdc++.so.6
        NEW_LIB=newer-libstdc++.so.6
        LIB_FOLDER=/usr/lib/x86_64-linux-gnu
        echo
        echo must replace $LIB_FOLDER/$LIB with $NEW_LIB
        echo this is a system-wide global library
        echo
        read -p "replace the system library globally? " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
            exit 1
        fi
        set -x
        sudo cp ../$NEW_LIB $LIB_FOLDER
        sudo ln -sf $LIB_FOLDER/$NEW_LIB $LIB_FOLDER/libstdc++.so.6
        set +x
        echo
    fi

    echo
    echo starting $GLAM
    ./glamoroustoolkit GlamorousToolkit.image st ../load.st --no-quit --interactive

popd >& /dev/null

git status
